from pygame import (
    # keyboard map
    # WASD
    K_RSHIFT,
    K_w as WASD_UP,
    K_a as WASD_DOWN,
    K_s as WASD_LEFT,
    K_d as WASD_RIGHT,
    K_SPACE as WASD_JUMP,
    K_RCTRL as KEY_ATTACK,
    K_RSHIFT as KEY_ENERGY,
    K_RALT as KEY_GROUND,
    K_RETURN as KEY_PAUSE,
    # ARROWS
    K_UP as ARR_UP,
    K_DOWN as ARR_DOWN,
    K_LEFT as ARR_LEFT,
    K_RIGHT as ARR_RIGHT,
    # controller map
    CONTROLLER_AXIS_LEFTX as MAIN_HORIZONTAL,
    CONTROLLER_AXIS_LEFTY as MAIN_VERTICAL,
    CONTROLLER_AXIS_RIGHTX as AUX_HORIZONTAL,
    CONTROLLER_AXIS_RIGHTY as AUX_VERTICAL,
    CONTROLLER_BUTTON_A as JOY_JUMP,
    CONTROLLER_BUTTON_X as JOY_ATTACK,
    CONTROLLER_BUTTON_Y as JOY_ENERGY,
    CONTROLLER_BUTTON_START as JOY_PAUSE,
    CONTROLLER_BUTTON_B as JOY_GROUND,
    # DEBUG mode controls
    K_ESCAPE as FORCE_QUIT,
    K_KP0 as VIEW_FPS,
    K_KP1 as VIEW_COLLISION,
    K_KP2 as VIEW_SENSORS,
    K_KP3 as PLACE_OBJECT,
    K_KP_ENTER as LEVEL_SAVE
) # This is the default controls